components:
- layout_properties: {grid_position: 'PKAPRJ,IIXCOW'}
  name: image_1
  properties: {height: 627, source: _/theme/Screenshot 2025-01-09 at 10.09.35 PM.png}
  type: Image
- event_bindings: {click: primary_color_1_click}
  layout_properties: {grid_position: 'PKAPRJ,YRNEVO'}
  name: primary_color_1
  properties: {icon: 'fa:close', role: primary-color, text: ''}
  type: Button
container:
  properties: {col_widths: '{"IIXCOW":55,"YRNEVO":5}'}
  type: ColumnPanel
is_package: true
